[package]
name = "hello-world"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
soroban-token-sdk = "21.7.4"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
